### PR TITLE
Remove uses of the `eq` primitive, which is slated for removal.

### PR DESCRIPTION
**Pull request by robdockins**
Minor changes made necessary by https://github.com/GaloisInc/saw-script/pull/1114.

### CODE REVIEW

**Comment by robdockins** [comment]
https://github.com/GaloisInc/saw-script/pull/1114 has now landed.  I'm not sure exactly how up-to-date you are keeping on SAW versions, but these changes will need to go in once you update past that point.

**Comment by msaaltink** [comment]
Good to have this ready.  I take it that there's no way to write something that's valid now and will also work when we update saw?

**Comment by robdockins** [comment]
I think all the changes except the ones sending `eq Nat` to `equalNat` should be backward compatible.  Unfortunately, `equalNat` is not recognized as the head of a valid rewrite rule until after https://github.com/GaloisInc/saw-script/pull/1114

**Comment by msaaltink** [comment]
I think the Nat rules were only used to make the formulas more readable while developing the proofs, and are not needed for the proofs to succeed.  I'll do an experiment locally to see if anything breaks if they are removed; there might be an interaction I've forgotten.

**Pull request merged**
